#!/usr/bin/env python3
"""Build Beast Tamer v1.1: the monsters-only JobData patch.

Live-proven mechanism (goblin probe): the Dragon Check consumes
JobData.MonsterGraphic. Setting a monster job's MonsterGraphic to 15 (Dragon
family value) makes the check pass for that species, while rendering and all
other gameplay ignore the field (PSX decomp: the check is its only gameplay
reader; sprites resolve via SpritesheetID).

The patch: every GENERIC monster job (vanilla MonsterGraphic 1..14, i.e.
Chocobo..Behemoth families, jobs 94-135) gets MonsterGraphic=15. Dragons (15)
and Hydras (16) already pass. Humans have MonsterGraphic=0 and stay blocked.
Special/story monsters (Byblos, Automaton, Reaver, demons - graphic 0) are
intentionally NOT included: "all monsters" here means the tamable wild
families, mirroring the classic community patch's range.

Usage: python tools/build_jobdata.py
Writes: mod/fftivc.beasttamer/FFTIVC/tables/enhanced/JobData.xml
"""
from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TEMPLATE = Path(r"C:/Reloaded-II/Mods/fftivc.utility.modloader/TableData/JobData.xml")
OUT = REPO / "mod/fftivc.beasttamer/FFTIVC/tables/enhanced/JobData.xml"

DRAGON_GRAPHIC = 15


def main() -> None:
    if not TEMPLATE.exists():
        sys.exit(f"ERROR: vanilla JobData template not found: {TEMPLATE}")
    tree = ET.parse(TEMPLATE)
    entries = tree.getroot().find("Entries")
    picked: list[tuple[int, int, str]] = []
    for job in entries.findall("Job"):
        jid = int(job.findtext("Id"))
        graphic = int(job.findtext("MonsterGraphic", "0"))
        if 1 <= graphic <= 14:
            picked.append((jid, graphic))
    # 14 families x 3 (jobs 94-135) + 5 special-encounter duplicates (169-173:
    # Red Panther, Goblin, Black Goblin, Bomb, Chocobo variants)
    if len(picked) != 47:
        sys.exit(f"ERROR: expected 47 generic monster jobs, got {len(picked)}")

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "",
        "<!--",
        "  GENERATED by tools/build_jobdata.py - do not hand-edit.",
        "  Beast Tamer v1.1 (monsters-only): every generic monster job's MonsterGraphic is",
        "  set to 15 (Dragon family) so the hardcoded Dragon Check in formulas 0x5A-0x5D",
        "  passes for all wild monster species. Rendering does not consume this field",
        "  (live-proven); humans keep MonsterGraphic=0 and stay excluded; Dragons/Hydras",
        f"  (15/16) already pass. Jobs emitted: {len(picked)}.",
        "-->",
        "",
        "<JobTable>",
        "  <Version>1</Version>",
        "  <Entries>",
    ]
    for jid, graphic in picked:
        lines.append("    <Job>")
        lines.append(f"      <Id>{jid}</Id>")
        lines.append(f"      <MonsterGraphic>{DRAGON_GRAPHIC}</MonsterGraphic>")
        lines.append("    </Job>")
    lines += ["  </Entries>", "</JobTable>", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"[beasttamer] wrote {OUT} ({len(picked)} jobs -> graphic {DRAGON_GRAPHIC})")


if __name__ == "__main__":
    main()
